package phrases

import "math/rand"

var Phrases = []string {
  "Reticulating splines...",
  "Generating witty dialog...",
  "Swapping time and space...",
  "Spinning violently around the y-axis...",
  "Tokenizing real life...",
  "Bending the spoon...",
  "Filtering morale...",
  "Don't think of purple hippos...",
  "Checking the gravitational constant in your locale...",
  "Reconfoobling energymotron...",
  "Don't panic...",
  "Spinning the wheel of fortune...",
  "Loading the enchanted bunny...",
  "I feel like im supposed to be loading something. . .",
  "Adjusting flux capacitor...",
  "Let's take a mindfulness minute...",
  "Listening for the sound of one hand clapping...",
  "Keeping all the 1's and removing all the 0's...",
  "Putting the icing on the cake. The cake is not a lie...",
  "Cleaning off the cobwebs...",
  "Making sure all the i's have dots...",
  "Connecting Neurotoxin Storage Tank...",
  "Granting wishes...",
  "Spinning the hamster…",
  "Constructing additional pylons...",
  "Roping some seaturtles...",
  "Locating Jebediah Kerman...",
  "Dividing by zero...",
  "Cracking military-grade encryption...",
  "Simulating traveling salesman...",
  "Proving P=NP...",
  "Entangling superstrings...",
  "Twiddling thumbs...",
  "Searching for plot device...",
  "Trying to sort in O(n)...",
  "Kindly hold on as we convert this bug to a feature...",
  "Kindly hold on as our intern quits vim...",
  "Installing dependencies...",
  "Switching to the latest JS framework...",
  "Updating dependencies...",
  "Please wait... Consulting the manual...",
  "Loading funny message...",
  "format C: ...",
  "Mining some bitcoins...",
  "Downloading more RAM..",
  "Updating to Windows Vista...",
  "Deleting System32 folder",
  "Initializing the initializer...",
  "Optimizing the optimizer...",
  "Running swag sticker detection...",
  "Pushing pixels...",
  "Building a wall...",
  "Updating Updater...",
  "Downloading Downloader...",
  "Debugging Debugger...",
  "Reading Terms and Conditions for you...",
  "Running with scissors...",
  "Discovering new ways of making you wait...",
  "Please wait while we serve other customers...",
  "Feeding unicorns...",
  "Rupturing the subspace barrier...",
  "Creating an anti-time reaction...",
  "Converging tachyon pulses...",
  "Bypassing control of the matter-antimatter integrator...",
  "Adjusting the dilithium crystal converter assembly...",
  "Reversing the shield polarity...",
  "Disrupting warp fields with an inverse graviton burst...",
}

func Random() string {
	return Phrases[rand.Intn(len(Phrases))]
}
